#!/usr/bin/env bash
#
# One-shot bootstrap for a fresh Ubuntu 24.04 VPS: installs Postgres, Node,
# pnpm and Caddy; clones and builds Irice; generates real secrets (never
# baked into this script or typed by hand); and starts everything as a
# systemd service behind automatic HTTPS.
#
# Run as root, once, on a brand-new box:
#   DOMAIN=shop.example.com REPO_URL=https://github.com/aliaslany/Irice.git \
#     bash deploy/setup.sh
#
# DOMAIN is optional — omit it to serve plain HTTP on the server's IP while
# you're still testing (see deploy/README.md for why that's fine short-term
# and not fine for a real launch).
#
# Safe to re-run: it skips steps that already succeeded and always
# re-pulls/rebuilds/restarts the app, so it doubles as the update script —
# see deploy/deploy.sh, which is this same re-run logic on its own.
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/aliaslany/Irice.git}"
BRANCH="${BRANCH:-main}"
DOMAIN="${DOMAIN:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@${DOMAIN:-example.com}}"
APP_DIR=/opt/irice/app
ENV_FILE=/etc/irice/irice.env
CREDS_FILE=/root/IRICE_CREDENTIALS.txt

if [ "$(id -u)" -ne 0 ]; then
  echo "Run this as root." >&2
  exit 1
fi

echo "==> Installing packages (Postgres, Node, Caddy, git)"
apt-get update -qq
apt-get install -y -qq curl git gnupg ca-certificates lsb-release

# PostgreSQL 16 from the distro repo is fine for this app's scale.
apt-get install -y -qq postgresql postgresql-contrib
systemctl enable --now postgresql

# Node 22 via NodeSource — the version this app is built against.
if ! command -v node >/dev/null || [ "$(node -v | grep -oE '^v[0-9]+' | tr -d v)" -lt 22 ]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash - >/dev/null
  apt-get install -y -qq nodejs
fi
corepack enable >/dev/null 2>&1 || npm install -g pnpm >/dev/null

# Caddy — automatic HTTPS with zero certbot/nginx config.
if ! command -v caddy >/dev/null; then
  # The key must be dearmored into apt's binary keyring format — writing the
  # raw ASCII-armored download straight to the keyring path (a mistake this
  # script had at first) makes every subsequent `apt-get update` fail on a
  # GPG signature error.
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    -o /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
fi

echo "==> Creating the irice system user and directories"
id -u irice >/dev/null 2>&1 || useradd --system --create-home --home-dir /opt/irice irice
mkdir -p "$APP_DIR" /etc/irice
chown -R irice:irice /opt/irice

echo "==> Cloning/updating the app (branch: $BRANCH)"
if [ -d "$APP_DIR/.git" ]; then
  sudo -u irice git -C "$APP_DIR" fetch origin "$BRANCH"
  sudo -u irice git -C "$APP_DIR" checkout "$BRANCH"
  sudo -u irice git -C "$APP_DIR" reset --hard "origin/$BRANCH"
else
  sudo -u irice git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
fi

echo "==> Setting up Postgres (role + database, only if they don't exist yet)"
DB_NAME=irice_prod
DB_USER=irice
if [ -f "$ENV_FILE" ]; then
  # Re-run: reuse the existing DB password rather than losing access to the
  # database by generating a new one the role doesn't have.
  DB_PASSWORD="$(grep -oP '(?<=^DATABASE_URL=postgres://irice:)[^@]+' "$ENV_FILE" || true)"
fi
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -hex 24)}"

sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD';"
sudo -u postgres psql -c "ALTER ROLE $DB_USER PASSWORD '$DB_PASSWORD';" >/dev/null
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;"

echo "==> Writing /etc/irice/irice.env"
if [ -f "$ENV_FILE" ]; then
  SESSION_SECRET="$(grep -oP '(?<=^SESSION_SECRET=).*' "$ENV_FILE" || true)"
  ADMIN_TOKEN="$(grep -oP '(?<=^ADMIN_TOKEN=).*' "$ENV_FILE" || true)"
fi
SESSION_SECRET="${SESSION_SECRET:-$(openssl rand -hex 32)}"
ADMIN_TOKEN="${ADMIN_TOKEN:-$(openssl rand -hex 24)}"
SITE_URL="${DOMAIN:+https://$DOMAIN}"
SITE_URL="${SITE_URL:-http://$(curl -s -4 ifconfig.me || echo localhost)}"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup.sh — edit freely, then: systemctl restart irice
NODE_ENV=production
DATABASE_URL=postgres://irice:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}
SESSION_SECRET=${SESSION_SECRET}
ADMIN_TOKEN=${ADMIN_TOKEN}
SITE_URL=${SITE_URL}
ALLOW_DEV_OTP_PEEK=false

# Real credentials required before this can take real orders — see
# deploy/README.md. Until both are set: checkout uses a FAKE payment
# gateway (no money moves) and OTP login codes only appear in
# `journalctl -u irice`, never reaching a real customer's phone.
# ZARINPAL_MERCHANT_ID=
# KAVENEGAR_API_KEY=

# Only after real enamad.ir registration — see components/EnamadBadge.tsx.
# ENAMAD_ID=
# ENAMAD_CODE=
EOF
chown root:irice "$ENV_FILE"
chmod 640 "$ENV_FILE"

echo "==> Installing dependencies and building"
cd "$APP_DIR"
sudo -u irice pnpm install --frozen-lockfile
sudo -u irice env $(grep -v '^#' "$ENV_FILE" | xargs) pnpm db:migrate
sudo -u irice env $(grep -v '^#' "$ENV_FILE" | xargs) pnpm build

echo "==> Installing the systemd service"
cp "$APP_DIR/deploy/irice.service" /etc/systemd/system/irice.service
systemctl daemon-reload
systemctl enable --now irice
systemctl restart irice

echo "==> Configuring Caddy"
if [ -n "$DOMAIN" ]; then
  sed -e "s/__DOMAIN__/${DOMAIN}/g" -e "s/__ADMIN_EMAIL__/${ADMIN_EMAIL}/g" \
    "$APP_DIR/deploy/Caddyfile.template" > /etc/caddy/Caddyfile
else
  # No domain yet — plain HTTP on the box's IP, so you can smoke-test before
  # DNS is pointed anywhere. Switch to the real Caddyfile.template once you
  # have a domain (see deploy/README.md).
  cat > /etc/caddy/Caddyfile <<EOF
:80 {
	reverse_proxy 127.0.0.1:3000
	encode gzip
}
EOF
fi
systemctl reload caddy 2>/dev/null || systemctl restart caddy

cat > "$CREDS_FILE" <<EOF
Irice admin token (for https://${DOMAIN:-<server-ip>}/admin/login):
  ${ADMIN_TOKEN}

Database password (irice role, irice_prod database):
  ${DB_PASSWORD}

Full generated config: ${ENV_FILE}
This file (${CREDS_FILE}) is for your reference only — delete it once
you've saved these somewhere safer (a password manager).
EOF
chmod 600 "$CREDS_FILE"

echo ""
echo "==> Done. Credentials written to $CREDS_FILE (read them now: cat $CREDS_FILE)"
echo "==> Site: ${SITE_URL}"
echo "==> Run 'pnpm db:seed' from $APP_DIR (as the irice user, with the env file loaded) if you want sample catalog data."
